export const data = [
    {
        id:'1',
        proposalNumber:'034823',
        clientName:'Cipla',
        plannedBudget:'34,289',
        disComp:'Media Spends',
        distyp:'Slab Based',
        reqDis:'20%',
        reason:'Lorem ipsum dolor sit amet...',
        stat: 'Approved',
        saleRep: 'Tom',
    },
    {
        id:'2',
        proposalNumber:'034823',
        clientName:'Cipla',
        plannedBudget:'34,289',
        disComp:'Media Spends',
        distyp:'Slab Based',
        reqDis:'20%',
        reason:'Lorem ipsum dolor sit amet...',
        stat: 'Approved',
        saleRep: 'Tom',
    },
    {
        id:'3',
        proposalNumber:'034823',
        clientName:'Cipla',
        plannedBudget:'34,289',
        disComp:'Media Spends',
        distyp:'Slab Based',
        reqDis:'20%',
        reason:'Lorem ipsum dolor sit amet...',
        stat: 'Approved',
        saleRep: 'Tom',
    },
    {
        id:'4',
        proposalNumber:'034823',
        clientName:'Cipla',
        plannedBudget:'34,289',
        disComp:'Media Spends',
        distyp:'Slab Based',
        reqDis:'20%',
        reason:'Lorem ipsum dolor sit amet...',
        stat: 'Approved',
        saleRep: 'Tom',
    },
    {
        id:'5',
        proposalNumber:'034823',
        clientName:'Cipla',
        plannedBudget:'34,289',
        disComp:'Media Spends',
        distyp:'Slab Based',
        reqDis:'20%',
        reason:'Lorem ipsum dolor sit amet...',
        stat: 'Approved',
        saleRep: 'Tom',
    },
    {
        id:'6',
        proposalNumber:'034823',
        clientName:'Cipla',
        plannedBudget:'34,289',
        disComp:'Media Spends',
        distyp:'Slab Based',
        reqDis:'20%',
        reason:'Lorem ipsum dolor sit amet...',
        stat: 'Approved',
        saleRep: 'Tom',
    }
];