export const data = [
    {
        id:'1',
        proposalNumber:'034823',
        agency:'Ogilvy',
        clientName:'GSK',
        brand:'Horlicks',
        objective:'Lorem',
        campaigns:'23',
        product:'Target',
        targetAud:'50',
        duration: '63 Days',
        targetReach: '75',
        bid:'CPM',
        freq:'Weekly',
        est:'62',
        net:'55',
        estMedi:'34',
        mngd:'95',
        tech:'42',
        dis:'20%',
        total:'6543'
    },
    {
        id:'2',
        proposalNumber:'034823',
        agency:'Ogilvy',
        clientName:'GSK',
        brand:'Horlicks',
        objective:'Lorem',
        campaigns:'23',
        product:'Target',
        targetAud:'50',
        duration: '63 Days',
        targetReach: '75',
        bid:'CPM',
        freq:'Weekly',
        est:'62',
        net:'55',
        estMedi:'34',
        mngd:'95',
        tech:'42',
        dis:'20%',
        total:'6543'
    },
    {
        id:'3',
        proposalNumber:'034823',
        agency:'Ogilvy',
        clientName:'GSK',
        brand:'Horlicks',
        objective:'Lorem',
        campaigns:'23',
        product:'Target',
        targetAud:'50',
        duration: '63 Days',
        targetReach: '75',
        bid:'CPM',
        freq:'Weekly',
        est:'62',
        net:'55',
        estMedi:'34',
        mngd:'95',
        tech:'42',
        dis:'20%',
        total:'6543'
    },
    {
        id:'4',
        proposalNumber:'034823',
        agency:'Ogilvy',
        clientName:'GSK',
        brand:'Horlicks',
        objective:'Lorem',
        campaigns:'23',
        product:'Target',
        targetAud:'50',
        duration: '63 Days',
        targetReach: '75',
        bid:'CPM',
        freq:'Weekly',
        est:'62',
        net:'55',
        estMedi:'34',
        mngd:'95',
        tech:'42',
        dis:'20%',
        total:'6543'
    },
    {
        id:'5',
        proposalNumber:'034823',
        agency:'Ogilvy',
        clientName:'GSK',
        brand:'Horlicks',
        objective:'Lorem',
        campaigns:'23',
        product:'Target',
        targetAud:'50',
        duration: '63 Days',
        targetReach: '75',
        bid:'CPM',
        freq:'Weekly',
        est:'62',
        net:'55',
        estMedi:'34',
        mngd:'95',
        tech:'42',
        dis:'20%',
        total:'6543'
    },
    {
        id:'6',
        proposalNumber:'034823',
        agency:'Ogilvy',
        clientName:'GSK',
        brand:'Horlicks',
        objective:'Lorem',
        campaigns:'23',
        product:'Target',
        targetAud:'50',
        duration: '63 Days',
        targetReach: '75',
        bid:'CPM',
        freq:'Weekly',
        est:'62',
        net:'55',
        estMedi:'34',
        mngd:'95',
        tech:'42',
        dis:'20%',
        total:'6543'
    }
];