export const data = [
    {
        id: '1',
        networkType: 'Lorem',
        adFormat: 'Text',
        measurement: 'Lorem',
        speciality: 'Lorem',
        objective: 'Lorem',
        demographics: 'Lorem',
        baseCPM: 'Lorem',
        baseCPC: 'Lorem',
        baseCPV: 'Lorem',
        taf: 'Lorem',
        msf: 'Lorem',
        dpf: 'Lorem',
    },
    {
        id: '2',
        networkType: 'Lorem',
        adFormat: 'Text',
        measurement: 'Lorem',
        speciality: 'Lorem',
        objective: 'Lorem',
        demographics: 'Lorem',
        baseCPM: 'Lorem',
        baseCPC: 'Lorem',
        baseCPV: 'Lorem',
        taf: 'Lorem',
        msf: 'Lorem',
        dpf: 'Lorem',
    },
    {
        id: '3',
        networkType: 'Lorem',
        adFormat: 'Text',
        measurement: 'Lorem',
        speciality: 'Lorem',
        objective: 'Lorem',
        demographics: 'Lorem',
        baseCPM: 'Lorem',
        baseCPC: 'Lorem',
        baseCPV: 'Lorem',
        taf: 'Lorem',
        msf: 'Lorem',
        dpf: 'Lorem',
    },
    {
        id: '4',
        networkType: 'Lorem',
        adFormat: 'Text',
        measurement: 'Lorem',
        speciality: 'Lorem',
        objective: 'Lorem',
        demographics: 'Lorem',
        baseCPM: 'Lorem',
        baseCPC: 'Lorem',
        baseCPV: 'Lorem',
        taf: 'Lorem',
        msf: 'Lorem',
        dpf: 'Lorem',
    },
    {
        id: '5',
        networkType: 'Lorem',
        adFormat: 'Text',
        measurement: 'Lorem',
        speciality: 'Lorem',
        objective: 'Lorem',
        demographics: 'Lorem',
        baseCPM: 'Lorem',
        baseCPC: 'Lorem',
        baseCPV: 'Lorem',
        taf: 'Lorem',
        msf: 'Lorem',
        dpf: 'Lorem',
    },
    {
        id: '6',
        networkType: 'Lorem',
        adFormat: 'Text',
        measurement: 'Lorem',
        speciality: 'Lorem',
        objective: 'Lorem',
        demographics: 'Lorem',
        baseCPM: 'Lorem',
        baseCPC: 'Lorem',
        baseCPV: 'Lorem',
        taf: 'Lorem',
        msf: 'Lorem',
        dpf: 'Lorem',
    }
];